### PR TITLE
Update license year 2019

### PR DESCRIPTION
**Pull request by EvertonMelo**
### Fix license of use, 
update 2019; 
Format ISO 8869-1;
----------------------------------------------------------------------------------------------------------------------
in Memoriam Guto Schiavon 
guto-schiavon_bitcoin
R.I.P pioneer and friend. 

#ripGUTO

### CODE REVIEW

**Comment by screeni** [comment]
Who is this ??

**Comment by screeni** [comment]
Google say BRAZILIAN Trader! Why add this man ??!

**Comment by EvertonMelo** [comment]
@screeni 
a friend who left, but the most [relevant](https://github.com/okcashpro/okcash/pull/13/commits/a71ce552f096a78e511d1d5cb488798d6372950b) is that. Do you have any questions about the code?

**Comment by screeni** [comment]
Okay in this situation Rest In Peace for your friend. Our condolences for him.
We need to update the wallet (react) in the second quarter. Start-up phase 3: OKblue

**Pull request merged**
